### ISSUE TITLE
¿Algún problema?

### ISSUE THREAD

**Issue by JJ** [dipzza/roomie-bot#2]
¿Tienes algún problema en el hito 2? ¿Se te puede echar una mano?

**Comment by dipzza** [comment]
Ayer estuve gran parte del día fuera y al no tener experiencia con logging o bots de telegram me ha costado un poco decidir, además me interesaba probar Rust pero no me han acabado de convencer las librerías que tiene para telegram (porque me cuesta entenderlas más que las de Python, ejemplos sin comentar, menos comunidad / tutoriales y el no tener experiencia con el lenguaje).

Voy a hacer una decisión inicial ahora mismo pero cualquier consejo si otra herramienta se adapta mejor al problema es bienvenido. Gracias por la preocupación de ofrecer ayuda.

**Comment by JJ** [comment]
Ánimo.
